### ISSUE TITLE
Custom Error message Influences test result.

### ISSUE THREAD

**Issue by AZWN** [metaborg/nabl#109]
**Bug description**
Custom error messages influence test results.

**Versions**
Spoofax 3, version 0.19.2 - develop

**Steps to reproduce the behavior**
1. Checkout https://github.com/JonathanBrouwer/master-thesis/commit/416852a337936338d427ed4673fc94a7eb693b06
2. Build and test project
3. Change `type_check.stx:83` to `expectBetaEq((empty_scope(), e_type), (s, t')) | error $[Custom Message].`
4. Rebuild and run tests.

**Observed behavior**
First test run, 89/96 tests pass. The second run 85/96 tests pass.

**Expected behavior**
Both test runs should have the same passing/failing tests.

**Additional context**
Originally reported by @JonathanBrouwer.

**Comment by JonathanBrouwer** [comment]
The following four tests fail if you add this:
```
"type via var" in typecheck_base
"variable via type assert" in typecheck_infer
"double term" in tricky_types
"tricky 5 simple" in tricky_types
```

**Comment by AZWN** [comment]
Possibly related: https://github.com/metaborg/nabl/issues/79
